type Query {
  paths: [Path!]!
	path(id: ID!): Path!
}

type Path {
	id: ID!
	name: String!
	metro: Metro!
	# stations: [Station!]!
	# links: [PathLink!]
}

type Mutation {
  createPath(input: CreatePathInput!): Path!
  updatePath(id: ID!, input: UpdatePathInput!): Path!
  removePath(id: ID!): Path!
}

type Subscription {
  pathCreated: Path!
}

input CreatePathInput {
  name: String!
  metro_id: ID!
}

input UpdatePathInput {
  name: String
  metro_id: ID
}