type Query {
  paths: [Path!]!
	path(id: ID!): Path!
}

type Path {
	id: ID!
	name: String!
	metro: Metro!
	stations: [Station!]!
	links: [PathLink!]
}

type Mutation {
  createPath(input: CreatePathInput!): Path!
  updatePath(id: ID!, input: UpdatePathInput!): Path!
  removePath(id: ID!): Path!

  craeatePathLink(input: CreatePathLinkInput!): PathLink
}

type Subscription {
  pathCreated: Path!
}

input CreatePathInput {
  name: String!
  metro_id: ID!
}

input UpdatePathInput {
  name: String
  metro_id: ID
}

type PathLink {
	path: Path!
	linked_path: Path!
}

input CreatePathLinkInput {
  path_id: ID!
  linked_id: ID!
}