type Query {
  stations: [Station!]!
	station(id: ID!): Station!
}

type Mutation {
  createStation(input: CreateStationInput!): Station!
  updateStation(id: ID!, input: UpdateStationInput!): Station!
  removeStation(id: ID!): Station!
}

type Subscription {
  stationCreated: Station!
}

type Station {
	id: ID!
	name: String!
	path: Path!
	forward: Station
	backward: Station
	has_path_link: Boolean
	# StationLink: [StationLink!]
}

input CreateStationInput {
  name: String!
  path_id: ID!
  backward_id: Int
  forward_id: Int
}

input UpdateStationInput {
  name: String
}