type Query {
  stations: [Station!]!
	station(id: ID!): Station!

  stationLinks: [StationLink!]!
  stationLink(id: ID!): StationLink!
}

type Mutation {
  createStation(input: CreateStationInput!): Station!
  updateStation(id: ID!, input: UpdateStationInput!): Station!
  removeStation(id: ID!): Station!

  craeateStationLink(input: CreateStationLinkInput!): StationLink
}

type Subscription {
  stationCreated: Station!
}

type Station {
	id: ID!
	name: String!
	path: Path!
	forward: Station
	backward: Station
	has_path_link: Boolean
	StationLink: [StationLink!]
}

type StationLink {
	station: Station!
	linked_station: Station!
}

input CreateStationInput {
  name: String!
  path_id: ID!
  backward_id: Int
  forward_id: Int
}

input UpdateStationInput {
  name: String
}

input CreateStationLinkInput {
  station_id: ID!
  linked_id: ID!
}